hexojs/hexo-renderer-markdown-it

- lib/renderer.js
- test/index.js
Small change here -- if the plugins array provides an object instead of a string options can be passed to the plugin.
```yaml
markdown:
plugins:
- name: markdown-it-foo
options:
param: value
```
> support passing options to markdown-it plugins

- package.json
A new official markdown-it plugin, [repository here](https://github.com/markdown-it/markdown-it-cjk-breaks).
> Add markdown-it-cjk-breaks plugin

- .npmignore
- package.json
`npm publish --dry-run` result is following.
```sh
$ npm publish --dry-run
npm notice
npm notice package: hexo-renderer-markdown-it@3.4.2
npm notice === Tarball Contents ===
npm notice 1.5kB package.json
npm notice 1.1kB LICENSE
npm notice 1.9kB README.md
npm notice 1.9kB lib/anchors.js
npm notice 692B  lib/renderer.js
```
> chore: specify files to packaging

- README.md
Current coveralls badge link is old.
> chore: update coveralls status badge

- README.md
- index.js
mainly to enable anchor links to be compatible with [`toc()`](https://hexo.io/docs/helpers#toc) helper. Fixes https://github.com/theme-next/hexo-theme-next/issues/1168
All defaults are set in consistent with [hexo-renderer-marked](https://github.com/hexojs/hexo-renderer-marked).
cc @anthonyhan
> fix: set default config

- README.md
- index.js
- lib/anchors.js
- test/fixtures/outputs/anchors.html
- test/index.js
noticed `Object.assign()` doesn't do deep cloning,
In the following config, the defaults `level` and `collisionSuffix` are not parsed to the plugin in current behavior.
``` yml
markdown:
anchors:
permalink: true
```
This PR ensure defaults are handled correctly, so that `level` and `collisionSuffix` are retained.
---
also fixed an issue where duplicate titles are not handled correctly, should be `Object.prototype.hasOwnProperty()`, not `Object.prototype.isPrototypeOf()`
> fix: handle defaults correctly

- README.md
- index.js
- lib/anchors.js
- package.json
- test/fixtures/outputs/anchors.html
- test/index.js
BREAKING CHANGE: anchors retain case by default
Noticed while reviewing https://github.com/hexojs/hexo-renderer-markdown-it/pull/94, this plugin currently uses [sluggo](https://www.npmjs.com/package/sluggo) library. This PR replaces it with hexo-util [`slugize()`](https://github.com/hexojs/hexo-util#slugizestr-options) used in hexo and hexo-renderer-marked.
This shares similar goal with https://github.com/hexojs/hexo-renderer-markdown-it/pull/90 to bring consistency with hexo-renderer-marked. I think there'll be no more breaking change for [v4](https://github.com/hexojs/hexo-renderer-markdown-it/pull/91). Later PRs are more on feature parity (features that enabled by default in hexo-renderer-marked).
> fix(anchors): utilize slugize() of hexo-util

- package.json
Replaced by slugize() https://github.com/hexojs/hexo-renderer-markdown-it/pull/95
> chore(deps): remove sluggo

- README.md
- index.js
- lib/anchors.js
- test/index.js
Fixes #101
How to use:
``` yml
markdown:
anchors:
permalink: true
permalinkSide: 'right'
permalinkSymbol: '#'
```
`#` should appear on the right side of each heading, instead of the default left.
> feat: permalinkSide

- README.md
- index.js
- lib/renderer.js
- test/fixtures/outputs/anchors.html
- test/fixtures/outputs/commonmark-deprecated.html
- test/fixtures/outputs/custom.html
- test/fixtures/outputs/default.html
- test/fixtures/outputs/plugins.html
- test/index.js
Currently when a preset is set, its options can't be overridden and anchor feature cannot be used.
Updated [wiki](https://github.com/hexojs/hexo-renderer-markdown-it/wiki/Advanced-Configuration#preset-options).
- BREAKING CHANGE: config syntax has been updated, old config compatibility is temporarily retained
* Old config
``` yml
markdown: 'commonmark'
```
* will be automatically converted to:
``` yml
markdown:
preset: 'commonmark'
```
- refactor(test): set default config
> feat: support preset and render options

- README.md
- lib/renderer.js
- test/fixtures/outputs/default-disable_rules.html
- test/fixtures/outputs/zero-enable_rules.html
- test/index.js
Based on #38 credit @jGleitz 
Some [rules](https://github.com/markdown-it/markdown-it#manage-rules) are enabled or disabled depending on the preset. For example, `zero` preset disable all rules, `enable_rules` allows enabling specific rules; `default` preset enables all rules, `disable_rules` is vice-versa.
Updated [wiki](https://github.com/hexojs/hexo-renderer-markdown-it/wiki/Advanced-Configuration#manage-rules).
> feat: options to enable/disable rules

- README.md
- test/index.js
The option is already supported (it's parsed to markdown-it by default).
Closes https://github.com/hexojs/hexo-renderer-markdown-it/issues/97
Added to [guide](https://github.com/hexojs/hexo-renderer-markdown-it/wiki/Advanced-Configuration#langprefix).
> test: 'langPrefix' option

- README.md
- index.js
- https://github.com/hexojs/hexo-util#slugizestr-options
> docs(slugize): default separator is a dash

- index.js
- lib/renderer.js
- test/index.js
Fix: #57 
It is mentioned in #57 no need to create a new markdonw-it instance for each file.
> perf(#57): avoid creating instance each time when render each file

- index.js
- lib/renderer.js
- test/index.js
- test/scripts/enable_unsafe_link.js
The [filter](https://github.com/hexojs/hexo-renderer-markdown-it#extensibility) won't be work after upgrade to [v6.0.0](https://github.com/hexojs/hexo-renderer-markdown-it/releases/tag/6.0.0)
The hexo [loadScripts after loadModules](https://github.com/hexojs/hexo/blob/f12a8db03b392bb5c32c0649302a3d0cc8768832/lib/hexo/load_plugins.js#L11)
When this plugin being required and loaded by [loadModules](https://github.com/hexojs/hexo/blob/f12a8db03b392bb5c32c0649302a3d0cc8768832/lib/hexo/load_plugins.js#L47), the `Renderer` constructed and the filter `markdown-it:renderer` was executed at this time.
https://github.com/hexojs/hexo-renderer-markdown-it/blob/4d4d4bdf74acfc8b11ac5021e5e2026ac2e62989/lib/renderer.js#L47
But the script that contains implementation of filter was loaded by …
> fix(#135): filter was executed before it was loaded

- lib/anchors.js
- test/index.js
After #135, using the same heading in different posts caused the rendered posts' anchor id to be add unnecessarily suffixes.
**_posts/post-1.md**
```markdown
---
title: Post 1
---
```
will be rendered to:
```html
<h2 id="Development">Development</h2>
<h2 id="Production">Production</h2>
```
---
**_posts/post-2.md**
```markdown
---
title: Post 2
---
```
will be rendered to:
```html
<h2 id="Development-2">Development</h2>
<h2 id="Production-2">Production</h2>
```
actually the result should as same as **_posts/post-1.md**.
> fix: clear title cache after rendering of a post

- README.md
- lib/images.js
- lib/renderer.js
- test/index.js
This pull request resolves #140, closes #141.
_\_posts/foo.md_
```markdown
```
will be rendered to:
```html
<p><img src="/post/foo/bar.svg"></p>
<p><img src="/post/foo/bar.svg"></p>
```
Note that for some local markdown editor previews, we need to use `![](foo/bar.svg)` to display the image correctly. Adding support for this insertion format can bring users a good local writing experience.
> feat: add image options

- lib/renderer.js
- test/index.js
Support render inline (Single line rendering, without paragraph wrap) which is useful when rendering text inside plugins and tags.
For instance, I would be able to render caption and content without p tag with `inline: true` option:
```js
hexo.extend.tag.register(
"figure",
function ([caption], content) {
return `<figure>${hexo.render.renderSync(
{
text: content,
engine: "markdown",
},
{
inline: true,
}
)}<figcaption>${hexo.render.renderSync(
{
text: caption,
engine: "markdown",
},
{
inline: true,
}
)}</figcaption></figure>`;
},
{ ends: true }
);
```
> feat: support renderInline

- lib/renderer.js
fixed cannot find some markdown-it plugin which installed by yarn berry.
error logs before fixed:
```log
ERROR Plugin load failed: hexo-renderers
Error: Cannot find module 'markdown-it-table-of-contents'
Require stack:
- D:\Repositories\hexo-renderers\lib\dist\markdown-it\renderer.js
- D:\Repositories\hexo-renderers\lib\dist\renderer-markdown-it.js
- D:\Repositories\hexo-renderers\lib\dist\renderer-loader.js
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:931:15)
at Function.Module._load (internal/modules/cjs/loader.js:774:27)
at Module.require (internal/modules/cjs/loader.js:1003:19)
at require (internal/modules/cjs/helpers.js:107:18)
at D:\Repositories\hexo-renderers\lib\dist\markdown-it\renderer.js:38:39
at Array.reduce (<anonymous>)
at new Renderer …
```
> fix: cannot find installed markdown-it plugin by yarn v3 monorepo

- lib/images.js
- test/index.js
When using the `images:` config option, the `alt` tag doesn't get added to the attributes.
**Steps to Reproduce**
- Set images in hexo `_config.yml` file
``` yaml
markdown:
images:
lazyload: true // Need at least one option, this is just an example
```
- Note the generated `<img .../>` tags in HTML don't have any `alt` attributes
Use the `token.content` which contains the "alt text" from the markdown image.
_Example markdown image_
_What's available in the context during debugging_
_Note: I'm not sure if it would be better to fix this up the call-chain :shrug:_
- Fixes #205
> Fixes "alt" tag not showing, when `images` option is used
